apiVersion: apps/v1
kind: Deployment
metadata:
  name: <your name>
  labels:
    app: todo
spec:
  replicas: <select as per your choice>
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: <your image>
        ports:
        - containerPort: <your port>
