apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: todo-pv
provisioner: k8s.io/minikube-hostpath
parameters:
  type: fast
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: rishikeshops/todo-app