apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    
    
# After creating this file , run below command:
# kubectl apply -f <yaml file name>
