apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: todo-service
  labels:
    app: todo
spec:
  type: ClusterIP
  selector:
    app: todo
  ports:
    - name: todo-service-port
      port: 80
      protocol: TCP
      targetPort: 8000