apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: production
  labels:
    app: todo
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - name: todo-service-port
      port: 8000
      targetPort: 8000
      nodePort: 30001