apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: production
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: rishikeshops/todo-app
        env:
          - name: PLAYER_INITIAL_LIVES 
            valueFrom:
              configMapKeyRef:
                name: todo-configmap        # The ConfigMap this value comes from.
                key: player_initial_lives # The key to fetch.
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: DB_PASS
        ports:
         - containerPort: 8000